### ISSUE TITLE
React.PropTypes validation function is deprecated

### ISSUE THREAD

**Issue by lovato** [thebakeryio/generator-rn#20]
![image](https://cloud.githubusercontent.com/assets/1213774/18372657/a2639dd0-7614-11e6-86f3-9be210a6a534.png)

**Comment by lovato** [comment]
I am using latest node and react-native versions.

~/c/m/r/MyReactApp ❯ react-native --version
react-native-cli: 1.0.0
react-native: 0.28.0
~/c/m/r/MyReactApp ❯ node --version
v6.4.0
~/c/m/r/MyReactApp ❯

**Comment by callmephilip** [comment]
Hey Marco, this generator is deprecated in favor of this -> https://github.com/bakery/baker. I suggest you take a look at the baker and see if it fits your needs
